service: cptac-sync

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2
  tags:
    costcenter: pbc
  stackTags:
    costcenter: pbc
  deploymentBucket:
    tags:
      costcenter: pbc
  httpApi:
      cors: true
  environment:
    BSI_SECRET: ${opt:stage, self:provider.stage}-bsi-cptac-service
    CDR_SECRET: ${opt:stage, self:provider.stage}-cdr-service
    BSI_BASE_URL: ${self:custom.bsi_base_url.${opt:stage, self:provider.stage}, self:bsi_base_url.dev}
    CDR_BASE_URL: ${self:custom.cdr_base_url.${opt:stage, self:provider.stage}, self:cdr_base_url.dev}
    BSI_RECEIPTS: ${self:custom.table_prefix}-receipts
    BSI_RECEIPTS_SYNC: ${self:custom.table_prefix}-receipts-sync
    BSI_ISCANS: ${self:custom.table_prefix}-iscans
    BSI_ISCANS_SYNC: ${self:custom.table_prefix}-iscans-sync
    BSI_MOLECULARQCS: ${self:custom.table_prefix}-molecularqcs
    BSI_MOLECULARQCS_SYNC: ${self:custom.table_prefix}-molecularqcs-sync
    BSI_PROTEINS: ${self:custom.table_prefix}-proteins
    BSI_PROTEINS_SYNC: ${self:custom.table_prefix}-proteins-sync
    LATEST_RECORD: ${self:custom.table_prefix}-latest-record
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: 'arn:aws:secretsmanager:${opt:region, self:provider.region}:${aws:accountId}:secret:${opt:stage, self:provider.stage}-bsi-cptac-service-*'
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: 'arn:aws:secretsmanager:${opt:region, self:provider.region}:${aws:accountId}:secret:${opt:stage, self:provider.stage}-cdr-service-*'
    - Effect: Allow
      Action:
        - dynamodb:ListStreams
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:${aws:accountId}:table/${self:custom.table_prefix}-*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: 'arn:aws:lambda:${opt:region, self:provider.region}:${aws:accountId}:function:${self:service}-${opt:stage, self:provider.stage}-pull-recent-*'
package:
  exclude:
    - client/**
    - README.md
    - .gitignore

functions:
  # Scheduled Tasks
  pull-recent-changes:
    handler: handlers.pullrecentchanges
    timeout: 600
    memorySize: 256
    alarms:
      - name: functionErrors
        threshold: 7
        period: 10800
    events:
      - schedule:
          name: ${self:service}-${opt:stage, self:provider.stage}-iscan-timer
          rate: cron(0 10-23 * * ? *)
          enabled: false
  # Stream Subscriptions
  sync-receipt:
    handler: handlers.syncreceipt
    timeout: 120
    memorySize: 256
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          maximumRetryAttempts: 0
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - ShipmentReceipts
              - StreamArn
  sync-molecularqc:
    handler: handlers.syncmolecularqc
    timeout: 120
    memorySize: 256
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          maximumRetryAttempts: 0
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Molecularqcs
              - StreamArn
  sync-iscan:
    handler: handlers.synciscan
    timeout: 120
    memorySize: 256
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          maximumRetryAttempts: 0
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Iscans
              - StreamArn
  sync-protein:
    handler: handlers.syncprotein
    timeout: 120
    memorySize: 256
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          maximumRetryAttempts: 0
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Proteins
              - StreamArn
  # Shipment Receipts API
  get-receipt:
    handler: handlers.getreceipt
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /receipt/{id}
          method: get
          authorizer:
            type: aws_iam
  get-receipt-sync:
    handler: handlers.getreceiptsync
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /receiptsync/{id}
          method: get
          authorizer:
            type: aws_iam
  rebuild-receipt:
    handler: handlers.rebuildreceipt
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /receipt/{id}
          method: put
          authorizer:
            type: aws_iam
  resync-receipt:
    handler: handlers.resyncreceipt
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /receiptsync/{id}
          method: put
          authorizer:
            type: aws_iam
  pull-recent-receipts:
    handler: handlers.pullrecentreceipts
    memorySize: 256
    timeout: 600
  # IScan API
  get-iscan:
    handler: handlers.getiscan
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /iscan/{id}
          method: get
          authorizer:
            type: aws_iam
  get-iscan-sync:
    handler: handlers.getiscansync
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /iscansync/{id}
          method: get
          authorizer:
            type: aws_iam
  rebuild-iscan:
    handler: handlers.rebuildiscan
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /iscan/{id}
          method: put
          authorizer:
            type: aws_iam
  resync-iscan:
    handler: handlers.resynciscan
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /iscansync/{id}
          method: put
          authorizer:
            type: aws_iam
  pull-recent-iscan:
    handler: handlers.pullrecentiscans
    timeout: 600
    memorySize: 256
  # Molecular QC API
  get-molecularqc:
    handler: handlers.getmolecularqc
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /molecularqc/{id}
          method: get
          authorizer:
            type: aws_iam
  get-molecularqc-sync:
    handler: handlers.getmolecularqcsync
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /molecularqcsync/{id}
          method: get
          authorizer:
            type: aws_iam
  rebuild-molecularqc:
    handler: handlers.rebuildmolecularqc
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /molecularqc/{id}
          method: put
          authorizer:
            type: aws_iam
  resync-molecularqc:
    handler: handlers.resyncmolecularqc
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /molecularqcsync/{id}
          method: put
          authorizer:
            type: aws_iam
  pull-recent-molecularqc:
    handler: handlers.pullrecentmolecularqcs
    timeout: 600
    memorySize: 256
  # Protein API
  get-protein:
    handler: handlers.getprotein
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /protein/{id}
          method: get
          authorizer:
            type: aws_iam
  get-protein-sync:
    handler: handlers.getproteinsync
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /proteinsync/{id}
          method: get
          authorizer:
            type: aws_iam
  rebuild-protein:
    handler: handlers.rebuildprotein
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /protein/{id}
          method: put
          authorizer:
            type: aws_iam
  resync-protein:
    handler: handlers.resyncprotein
    timeout: 29
    memorySize: 256
    events:
      - httpApi:
          path: /proteinsync/{id}
          method: put
          authorizer:
            type: aws_iam
  pull-recent-proteins:
    handler: handlers.pullrecentproteins
    timeout: 600
    memorySize: 256
  pull-recent-entity-async:
    handler: handlers.pullrecententityasync
    timeout: 5
    memorySize: 256
    events:
      - httpApi:
          path: /pullrecent/{entity}
          method: put
          authorizer:
            type: aws_iam

resources:
  # DynamoDB
  - ${file(sls-resources/dynamodb-shipment-receipts.yml)}
  - ${file(sls-resources/dynamodb-shipment-receipts-sync.yml)}
  - ${file(sls-resources/dynamodb-molecularqcs.yml)}
  - ${file(sls-resources/dynamodb-molecularqcs-sync.yml)}
  - ${file(sls-resources/dynamodb-iscans.yml)}
  - ${file(sls-resources/dynamodb-iscans-sync.yml)}
  - ${file(sls-resources/dynamodb-proteins.yml)}
  - ${file(sls-resources/dynamodb-proteins-sync.yml)}
  - ${file(sls-resources/dynamodb-latest-record.yml)}
  # Cognito
  - ${file(sls-resources/cognito-user-pool.yml)}
  - ${file(sls-resources/cognito-identity-pool.yml)}
  # S3
  # TODO: Add www.domain.com redirect to domain.com

plugins:
  - serverless-finch
  - serverless-plugin-aws-alerts

custom:
  bsi_base_url:
    prod: 'https://rest.bsisystems.com/api/rest/'
    mirror: 'https://rest-mirror.bsisystems.com/api/rest/'
    dev: 'https://rest-mirror.bsisystems.com/api/rest/'
  cdr_base_url:
    prod: 'https://cptac3.cancer.gov/cptacdataservices/rest/'
    mirror: 'https://cptac3.cptac.net/cptacdataservices/rest/'
    dev: 'https://cptac3.cptac.net/cptacdataservices/rest/'
  table_prefix: ${self:service}-${opt:stage, self:provider.stage}
  client:
    bucketName: ${self:service}-${opt:stage, self:provider.stage}.vari-cptac.org
    distributionFolder: client/build
    errorDocument: index.html
  alerts:
    definitions:
      functionErrors:
        threshold: 3
        period: 600
        treatMissingData: notBreaching
    stages:
      - prod
    topics:
      alarm:
        topic: ${self:service}-${opt:stage, self:provider.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: anthony.watkins@vai.org
    alarms:
      - functionErrors