service: cptac-sync

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  profile: vai
  tags:
    costcenter: pbc
  stackTags:
    costcenter: pbc
  deploymentBucket:
    tags:
      costcenter: pbc
  environment:
    BSI_BASE_URL: 'https://rest-mirror.bsisystems.com/api/rest/'
    BSI_RECEIPTS: ${self:service}-${opt:stage, self:provider.stage}-receipts
    BSI_ISCANS: ${self:service}-${opt:stage, self:provider.stage}-iscans
    BSI_MOLECULARQCS: ${self:service}-${opt:stage, self:provider.stage}-molecularqcs
    LATEST_RECORD: ${self:service}-${opt:stage, self:provider.stage}-latest-record
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: 'arn:aws:secretsmanager:${opt:region, self:provider.region}:*:secret:bsi-cptac-service-SGLi6d'
    - Effect: Allow
      Action:
        - dynamodb:ListStreams
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:service}-${opt:stage, self:provider.stage}-*"
package:
  exclude:
    - client/**
    - README.md
    - .gitignore

functions:
  pull-recent-receipts:
    handler: handlers.pullrecentreceipts
    timeout: 600
    environment:
      BSI_RECEIPTS: ${self:service}-${opt:stage, self:provider.stage}-receipts
      LATEST_RECORD: ${self:service}-${opt:stage, self:provider.stage}-latest-record
    # events:
    #   - name: ${self:service}-${opt:stage, self:provider.stage}-receipts-timer
    #   - schedule: cron(0 6-19 * * ? *)
  sync-receipt:
    handler: handlers.syncreceipt
    timeout: 120
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - ShipmentReceipts
              - StreamArn
  get-receipt:
    handler: handlers.getreceipt
    events:
      - http:
          path: receipt/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer: aws_iam
  pull-recent-cases:
    handler: handlers.pullrecentcases
    timeout: 600
    # events:
    #   - name: ${self:service}-${opt:stage, self:provider.stage}-iscan-timer
    #   - schedule: cron(0 6-19 * * ? *)
  sync-iscan:
    handler: handlers.synciscan
    timeout: 120
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Iscans
              - StreamArn
  get-iscan:
    handler: handlers.getiscan
    events:
      - http:
          path: iscan/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer: aws_iam
  sync-molecularqc:
    handler: handlers.synciscan
    timeout: 120
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - Iscans
              - StreamArn
  get-molecularqc:
    handler: handlers.getmolecularqc
    events:
      - http:
          path: molecuarqc/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
          authorizer: aws_iam

resources:
  # DynamoDB
  - ${file(sls-resources/dynamodb-shipment-receipts.yml)}
  - ${file(sls-resources/dynamodb-shipment-receipts-sync.yml)}
  - ${file(sls-resources/dynamodb-molecularqcs.yml)}
  - ${file(sls-resources/dynamodb-molecularqcs-sync.yml)}
  - ${file(sls-resources/dynamodb-iscans.yml)}
  - ${file(sls-resources/dynamodb-iscans-sync.yml)}
  - ${file(sls-resources/dynamodb-latest-record.yml)}
  # Cognito
  - ${file(sls-resources/cognito-user-pool.yml)}
  - ${file(sls-resources/cognito-identity-pool.yml)}
  # S3
  # TODO: Add www.domain.com redirect to domain.com

plugins:
  - serverless-finch

custom:
  client:
    bucketName: ${self:service}-${opt:stage, self:provider.stage}.aws.vai.org
    distributionFolder: client/build