Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}-${opt:stage, self:provider.stage}-user-pool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      UserPoolTags:
        costcenter: pbc

  CognitoUserPoolDataManager:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: "Access group for people to view and sync data"
      GroupName: "Data_Manager"
      RoleArn:
        Fn::GetAtt: [CognitoAuthRole, Arn]
      Precedence: 1
      UserPoolId:
        Ref: CognitoUserPool

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${self:service}-${opt:stage, self:provider.stage}-user-pool-client
      UserPoolId:
        Ref: CognitoUserPool
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient