Resources:
  Molecularqcs:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${opt:stage, self:provider.stage}-molecularqcs
      AttributeDefinitions:
        - AttributeName: caseId
          AttributeType: S
      KeySchema:
        - AttributeName: caseId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      Tags:
        - Key: costcenter
          Value: pbc