Resources:
  LatestRecord:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${opt:stage, self:provider.stage}-latest-record
      AttributeDefinitions:
        - AttributeName: topic
          AttributeType: S
      KeySchema:
        - AttributeName: topic
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: costcenter
          Value: pbc